export const TYPE = {
    AGREGAR_CARRITO:"AGREGAR_CARRITO",
    REMOVER_TODO_CARRITO:"REMOVER_TODO_CARRITO",
    REMOVER_UNO_CARRITO:"REMOVER_UNO_CARRITO",
    LIMPIAR_CARRITO:"LIMPIAR_CARRITO",
    FILTRAR_PRODUCTOS:"FILTRAR_PRODUCTOS"
};